//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaProje_6_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayakkabi
    {
        public int AyakkabiNo { get; set; }
        public string AyakkabiAdi { get; set; }
        public Nullable<int> AyakkabiKodu { get; set; }
        public string AyakkabiRengi { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
