//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaProje_6_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiyafet
    {
        public int KiyafetNo { get; set; }
        public string KiyafetAdi { get; set; }
        public Nullable<int> KiyafetKodu { get; set; }
        public string KumasTipi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
