//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemaProje_6_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sube
    {
        public int SubeNo { get; set; }
        public string SubeAdi { get; set; }
        public string SubeAdresi { get; set; }
        public string SubeIl { get; set; }
        public string SubeIlce { get; set; }
        public Nullable<int> CalisanSayisi { get; set; }
        public Nullable<int> Ciro { get; set; }
    }
}
